name: makeitminev2_5

services:
  gitserver:
    image: ${GIT_IMAGE}
    network_mode: host
    command: ["tail","-f","/dev/null"]
    volumes:
     - type: bind
       source: ${HOME}/projects
       target: /projects
       read_only: false
     - type: volume
       target: /projects/MakeItMineV2_5/.cache
     - type: bind
       source: /var/run/docker.sock
       target: /var/run/docker.sock
       read_only: false