[project]
name = "makeitminev2_5"
version = "0.0.1"
description = "Project build tools"
authors = [
    {name = "asburr",email = "asburr@hotmail.com"}
]
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
   "texttable",
   "pyinstaller"
]

[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"

[dependency-groups]
test = [
    "spyder-kernels (==3.1)"
]
